spring:
  application:
    name: message-api
server:
  port: 8081
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
jamon:
  crudo: this Message is from Qa configuration


